portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('proyecto/', include('proyecto.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/urls.py
from django.urls import path

from . import views

app_name = "proyecto"
urlpatterns = [
    path("", views.ProyectoListView.as_view(), name="index"),
    path("<int:pk>/", views.ProyectoDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.ProyectoUpdateView.as_view(), name="update"),
    path("create/", views.ProyectoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", views.ProyectoDeleteView.as_view(), name="delete"),
    #path("facturas", views.FacturaListView.as_view(), name="factura-index"),
    #path("facturas/<int:pk>/", views.FacturaDetailView.as_view(), name="factura-detail"),
    #path("facturas/<int:pk>/update/", views.FacturaUpdateView.as_view(), name="factura-update"),
    #path("facturas/create/", views.FacturaCreateView.as_view(), name="factura-create"),
    #path("facturas/<int:pk>/delete/", views.FacturaDeleteView.as_view(), name="factura-delete"),
]

proyecto/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save, post_delete
class tipo_proyecto(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class curso(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class imagen(models.Model):
    image = models.ImageField(upload_to="projects",blank=True)

    def __str__(self):
        return str(self.id)


class Proyecto(models.Model):
    """Model definition for Producto."""
    image = models.ImageField(upload_to="projects")
    nombre= models.CharField(max_length=50)
    fecha = models.DateTimeField(auto_now_add=True)
    tipo = models.ForeignKey(tipo_proyecto,on_delete=models.PROTECT)
    curso = models.ForeignKey(curso,on_delete=models.PROTECT)
    descripcion = models.TextField(blank=True)
    tiempo = models.CharField(max_length=50,blank=True)
    Grupo = models.TextField(blank=True)
    Completo = models.BooleanField(blank=True)
    imagen = models.ManyToManyField(imagen)
    class Meta:
        """Meta definition for Producto."""

        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return u'/tienda/%d' % self.id 

proyecto/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Proyecto,tipo_proyecto,curso
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSetFactory

# Productos views

class ProyectoListView(generic.ListView):
    model = Proyecto
    template_name = "list.html"


class ProyectoDetailView(generic.DetailView):
    model = Proyecto
    template_name = "detail.html"

class ProyectoCreateView(generic.CreateView):
    model = Proyecto
    fields = '__all__'
    template_name = "form.html"


class ProyectoUpdateView(generic.UpdateView):
    model = Proyecto
    fields = '__all__'
    template_name = "form.html"

class ProyectoDeleteView(generic.DeleteView):
    model = Proyecto
    template_name = "delete.html"
    success_url = reverse_lazy('proyectos:index')

proyecto/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>

proyecto/templates/delete.html
<form method="post">{% csrf_token %}
    <p>Seguro deseas eliminar "{{ object }}"?</p>
    <input type="submit" value="Confirmar">
</form>

proyecto/templates/detail.html
<h1>{{ proyecto.nombre }}</h1>
<img src="{{ proyecto.image.url }}" style="max-width: 200px">
<p>{{ proyecto.descripcion }}</p>
<p>{{ proyecto.tipo}}</p>
<p>{{ proyecto.curso }}</p>
<p>{{ proyecto.tiempo }}</p>
<p>{{ proyecto.Grupo }}</p>

{% for imagen in proyecto.imagen.all %}
<img src="{{ imagen.image.url }}" style="max-height: 100px; padding: 10px;">
{% endfor %}

<br>
<a href="{% url 'proyecto:update' proyecto.id %}">Actualizar</a>
<br>
<a href="{% url 'proyecto:index' %}">Todos los portafolios</a>
<br>
<a href="{% url 'proyecto:delete' proyecto.id %}">Eliminar</a>

proyecto/templates/form.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<h1>Proyectos</h1>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <input class="btn btn-primary" type="submit" value="Enviar" />
    {% endbuttons %}
</form>
{% endblock %}

proyecto/templates/list.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<a class="container padding-4 btn btn-primary" href="{% url 'proyecto:create' %}">Nuevo</a>
<div class="card" style="width: 18rem;">
    {% for Proyecto in object_list %}
        <img src="{{ Proyecto.image.url }}" style="max-height: 100px; padding: 10px;">
       
        <li class="list-group-item"><a href="{% url 'proyecto:detail' Proyecto.id %}">{{Proyecto.nombre}}</a></li>
    {% empty %}
        <li>No hay proyectos</li>
    {% endfor %}

 </div>

{% endblock %}